version: '3.3'

services:

  node:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - andela-network
    links:
      - mongodb
      
  mongodb:
    build:
      context: .
      dockerfile: mongo.dockerfile
    ports:
      - "27017:27017"
    networks:
      andela-network:
        aliases:
          - "mongo"

networks:
  andela-network:
    driver: bridge